"""initial migration

Revision ID: 24fb5ecd895d
Revises: 
Create Date: 2022-09-08 15:35:15.157086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24fb5ecd895d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_index('name', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'roles', ['name'], unique=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    # ### end Alembic commands ###
