"""add language to posts

Revision ID: 29759e2f518e
Revises: 4b4bd85a0b4d
Create Date: 2022-10-12 20:41:30.262291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29759e2f518e'
down_revision = '4b4bd85a0b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
